/* ═══════════════════════════════════════════════════════════════
   MARZENAPEDIA — Application JavaScript (Phase 1)
   ═══════════════════════════════════════════════════════════════
   Architecture:
   - Hash-based routing (#/article-slug, #/all, #/search/query)
   - index.json drives all article listing/search (auto-generated by GitHub Action)
   - Block tokenizer parser (extensible for Phase 3 :::blocks)
   - Article content fetched on-demand from /articles/{slug}.md
   - Last-edited dates from GitHub commits API (cached)
   - Dark mode via [data-theme] attribute on <html>
   - In-universe date system: ISO dates → CET display, used by timeline
   ═══════════════════════════════════════════════════════════════ */

// ─── CONFIGURATION ─────────────────────────────────────────────
const REPO_OWNER = 'helpimnotdmv';
const REPO_NAME = 'Marzenapedia';
const BRANCH = 'main';
const ARTICLES_PATH = 'articles';
const IMAGES_PATH = 'images';

const API_BASE = `https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}`;
const RAW_BASE = `https://raw.githubusercontent.com/${REPO_OWNER}/${REPO_NAME}/${BRANCH}`;
const INDEX_URL = `${RAW_BASE}/index.json`;

// ─── STATE ─────────────────────────────────────────────────────
const State = {
  view: 'home',              // 'home' | 'article' | 'all' | 'search'
  slug: null,
  index: null,               // { articles: [...], generated_at: "..." }
  articleCache: {},          // slug -> raw markdown
  lastEditCache: {},         // slug -> ISO date
  searchDebounceTimer: null,
  searchActiveResult: -1,
  scrollObserver: null
};

// ═══════════════════════════════════════════════════════════════
// THEME / DARK MODE
// ═══════════════════════════════════════════════════════════════
function initTheme() {
  const saved = localStorage.getItem('marzenapedia-theme');
  const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
  const theme = saved || (prefersDark ? 'dark' : 'light');
  applyTheme(theme);
}

function applyTheme(theme) {
  document.documentElement.setAttribute('data-theme', theme);
  const label = document.getElementById('theme-label');
  if (label) label.textContent = theme === 'dark' ? 'Light' : 'Dark';
}

function toggleTheme() {
  const current = document.documentElement.getAttribute('data-theme') || 'light';
  const next = current === 'dark' ? 'light' : 'dark';
  applyTheme(next);
  localStorage.setItem('marzenapedia-theme', next);
}

// ═══════════════════════════════════════════════════════════════
// CET CLOCK (in-universe time display)
// ═══════════════════════════════════════════════════════════════
function startCetClock() {
  const tick = () => {
    const now = new Date();
    // Force CET (Europe/Paris) display regardless of user's timezone
    const opts = {
      timeZone: 'Europe/Paris',
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
      hour12: false
    };
    const time = now.toLocaleTimeString('en-GB', opts);
    const el = document.getElementById('cet-time');
    if (el) el.textContent = time;
  };
  tick();
  setInterval(tick, 1000);
}

// In-universe date formatter — used by timeline blocks (Phase 3)
// Takes an ISO date string, returns "2 May 1952" formatted in CET context
function formatInUniverseDate(iso) {
  if (!iso) return '';
  const d = new Date(iso);
  if (isNaN(d.getTime())) return iso;
  return d.toLocaleDateString('en-GB', {
    timeZone: 'Europe/Paris',
    day: 'numeric',
    month: 'long',
    year: 'numeric'
  });
}

// ═══════════════════════════════════════════════════════════════
// HASH ROUTING
// Routes:  #/                  → home
//          #/all               → all articles
//          #/search/{q}        → search results
//          #/{slug}            → article
//          #/{slug}#{section}  → article with section anchor (handled separately)
// ═══════════════════════════════════════════════════════════════
function parseHash() {
  let hash = location.hash || '#/';
  if (!hash.startsWith('#/')) hash = '#/' + hash.replace(/^#/, '');
  const path = hash.slice(2); // strip "#/"

  if (!path || path === 'home') return { view: 'home' };
  if (path === 'all') return { view: 'all' };
  if (path.startsWith('search/')) {
    return { view: 'search', query: decodeURIComponent(path.slice(7)) };
  }
  // Article — may have a section anchor after a second "#"
  const [slug, section] = path.split('#');
  return { view: 'article', slug: decodeURIComponent(slug), section: section ? decodeURIComponent(section) : null };
}

function navigate(target, slugOrQuery) {
  if (target === 'home') {
    location.hash = '#/';
  } else if (target === 'all') {
    location.hash = '#/all';
  } else if (target === 'article' && slugOrQuery) {
    location.hash = '#/' + encodeURIComponent(slugOrQuery);
  } else if (target === 'search' && slugOrQuery) {
    location.hash = '#/search/' + encodeURIComponent(slugOrQuery);
  } else {
    location.hash = '#/';
  }
}

async function handleRoute() {
  const route = parseHash();
  State.view = route.view;
  State.slug = route.slug || null;

  document.getElementById('page-tabs').style.display = route.view === 'article' ? 'flex' : 'none';

  // Hide search dropdown
  const dd = document.getElementById('search-dropdown');
  if (dd) dd.classList.remove('visible');

  // Disconnect any existing scroll observer
  if (State.scrollObserver) { State.scrollObserver.disconnect(); State.scrollObserver = null; }

  if (route.view === 'home') await showHome();
  else if (route.view === 'all') await showAllArticles();
  else if (route.view === 'search') await showSearchResults(route.query);
  else if (route.view === 'article') await showArticle(route.slug, route.section);
}

window.addEventListener('hashchange', handleRoute);

// ═══════════════════════════════════════════════════════════════
// INDEX FETCHING
// Tries index.json first (the GitHub Action's output).
// Falls back to git/trees API if index.json is missing — useful
// before the Action has run for the first time.
// ═══════════════════════════════════════════════════════════════
async function fetchIndex() {
  if (State.index) return State.index;

  // Primary: try the auto-generated index.json
  try {
    const res = await fetch(`${INDEX_URL}?t=${Date.now()}`);
    if (res.ok) {
      const data = await res.json();
      if (data && Array.isArray(data.articles)) {
        State.index = data;
        return data;
      }
    }
  } catch (e) { /* fall through to fallback */ }

  // Fallback: derive from GitHub tree API
  console.warn('[Marzenapedia] index.json not found, falling back to GitHub tree API');
  try {
    const res = await fetch(`${API_BASE}/git/trees/${BRANCH}?recursive=1`);
    if (!res.ok) throw new Error('GitHub API unavailable');
    const data = await res.json();
    const mdFiles = (data.tree || []).filter(f =>
      f.path.startsWith(ARTICLES_PATH + '/') && f.path.endsWith('.md')
    );

    // Build a minimal index. Title/summary will be filled in lazily on demand.
    const articles = await Promise.all(mdFiles.map(async f => {
      const slug = f.path.replace(ARTICLES_PATH + '/', '').replace(/\.md$/, '');
      let title = slugToTitle(slug);
      let summary = '';
      let tags = [];
      try {
        const md = await fetchArticle(slug);
        title = extractTitle(md) || title;
        summary = extractSummary(md);
        const fm = parseFrontmatter(md);
        if (fm.tags) tags = fm.tags;
      } catch {}
      return { slug, title, summary, tags, infobox_type: null, last_edited: null };
    }));

    const fallback = { articles, generated_at: new Date().toISOString(), source: 'fallback' };
    State.index = fallback;
    return fallback;
  } catch (e) {
    console.error('[Marzenapedia] Index fetch failed entirely:', e);
    State.index = { articles: [], generated_at: null, source: 'empty' };
    return State.index;
  }
}

async function fetchArticle(slug) {
  if (State.articleCache[slug]) return State.articleCache[slug];
  const url = `${RAW_BASE}/${ARTICLES_PATH}/${slug}.md?t=${Date.now()}`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Article not found: ${slug}`);
  const text = await res.text();
  State.articleCache[slug] = text;
  return text;
}

// Last-edited date via GitHub commits API. Cached to be polite to rate limits.
async function fetchLastEdited(slug) {
  if (State.lastEditCache[slug] !== undefined) return State.lastEditCache[slug];
  // First check the index — it may have last_edited pre-baked
  if (State.index) {
    const entry = State.index.articles.find(a => a.slug === slug);
    if (entry && entry.last_edited) {
      State.lastEditCache[slug] = entry.last_edited;
      return entry.last_edited;
    }
  }
  try {
    const url = `${API_BASE}/commits?path=${ARTICLES_PATH}/${slug}.md&per_page=1`;
    const res = await fetch(url);
    if (!res.ok) throw new Error('commits API failed');
    const commits = await res.json();
    const date = commits?.[0]?.commit?.author?.date || null;
    State.lastEditCache[slug] = date;
    return date;
  } catch {
    State.lastEditCache[slug] = null;
    return null;
  }
}

// ═══════════════════════════════════════════════════════════════
// MARKDOWN PARSER — BLOCK TOKENIZER ARCHITECTURE
//
// The parser works in three passes:
//   1. extractFrontmatter — strip ::: frontmatter block from top
//   2. tokenizeBlocks     — split source into block tokens, where each
//                            block is either a fenced ::: block or raw markdown
//   3. renderBlocks       — for each token, dispatch to the right handler
//
// New block types in Phase 3 add a single entry to BLOCK_HANDLERS.
// Inline rules (bold, italic, links, wikilinks, images) are applied
// inside any block that contains prose.
// ═══════════════════════════════════════════════════════════════

const BLOCK_HANDLERS = {
  infobox: renderInfobox,
  figure: renderFigure,
  // Phase 3 will register: gallery, timeline, map, redirect, disambig,
  //   series, seealso, constitution, navbox, quote, audio, video
};

function parseMarkdown(md) {
  // Remove frontmatter — it's metadata, not rendered prose
  const { body } = extractFrontmatter(md);

  const tokens = tokenizeBlocks(body);
  return tokens.map(renderToken).join('\n');
}

// ─── FRONTMATTER ─────────────────────────────────────────────
// :::frontmatter
// tags: a, b, c
// date: 1952-05-02
// sources: Doc 44-B; Lévane Gazette #192
// :::
function extractFrontmatter(md) {
  const m = md.match(/^:::frontmatter\s*\n([\s\S]*?)\n:::\s*\n?/);
  if (!m) return { frontmatter: {}, body: md };
  return { frontmatter: parseFrontmatterBody(m[1]), body: md.slice(m[0].length) };
}

function parseFrontmatter(md) {
  return extractFrontmatter(md).frontmatter;
}

function parseFrontmatterBody(text) {
  const out = {};
  text.split('\n').forEach(line => {
    const m = line.match(/^([^:]+):\s*(.+)$/);
    if (!m) return;
    const key = m[1].trim().toLowerCase();
    const val = m[2].trim();
    if (key === 'tags') out.tags = val.split(/[,;]\s*/).map(t => t.trim()).filter(Boolean);
    else if (key === 'sources') out.sources = val.split(/;\s*/).map(s => s.trim()).filter(Boolean);
    else out[key] = val;
  });
  return out;
}

// ─── BLOCK TOKENIZER ─────────────────────────────────────────────
// Splits the markdown body into an array of tokens:
//   { type: 'block', name: 'infobox', args: '...', body: '...' }
//   { type: 'markdown', body: '...' }
function tokenizeBlocks(md) {
  const tokens = [];
  // Match :::name optional-args ... ::: (non-greedy)
  const re = /:::([a-z_][a-z0-9_-]*)([^\n]*)\n([\s\S]*?)\n:::/g;
  let lastIndex = 0;
  let match;
  while ((match = re.exec(md)) !== null) {
    if (match.index > lastIndex) {
      tokens.push({ type: 'markdown', body: md.slice(lastIndex, match.index) });
    }
    tokens.push({
      type: 'block',
      name: match[1].toLowerCase(),
      args: match[2].trim(),
      body: match[3]
    });
    lastIndex = match.index + match[0].length;
  }
  if (lastIndex < md.length) {
    tokens.push({ type: 'markdown', body: md.slice(lastIndex) });
  }
  return tokens;
}

function renderToken(tok) {
  if (tok.type === 'markdown') return renderMarkdownBlock(tok.body);
  const handler = BLOCK_HANDLERS[tok.name];
  if (handler) return handler(tok);
  // Unknown block — render as a notice so authors see the issue
  return `<div class="notice-box"><strong>Unknown block:</strong> <code>:::${tok.name}</code> — this block type isn't registered yet.</div>`;
}

// ─── INFOBOX BLOCK ─────────────────────────────────────────────
function renderInfobox(tok) {
  const lines = tok.body.split('\n');
  let title = '';
  let image = '';
  let caption = '';
  const sections = [{ header: null, rows: [] }];

  for (const line of lines) {
    const m = line.match(/^([^:]+):\s*(.*)$/);
    if (!m) continue;
    const key = m[1].trim();
    const val = m[2].trim();
    const lk = key.toLowerCase();
    if (lk === 'title') { title = val; continue; }
    if (lk === 'image') { image = val; continue; }
    if (lk === 'caption') { caption = val; continue; }
    if (lk === 'section') {
      sections.push({ header: val, rows: [] });
      continue;
    }
    sections[sections.length - 1].rows.push({ key, val: renderInline(val) });
  }

  let html = `<div class="infobox">`;
  if (title) html += `<div class="infobox-title">${escapeHtml(title)}</div>`;
  if (image) {
    html += `<div class="infobox-image"><img src="${resolveImagePath(image)}" alt="${escapeHtml(caption || title)}" onclick="openLightbox('${resolveImagePath(image)}','${escapeAttr(caption)}')">`;
    if (caption) html += `<div class="caption">${renderInline(caption)}</div>`;
    html += `</div>`;
  }
  html += `<table>`;
  for (const sec of sections) {
    if (sec.header) html += `<tr><td colspan="2" class="infobox-section-header">${escapeHtml(sec.header)}</td></tr>`;
    for (const r of sec.rows) html += `<tr><td>${escapeHtml(r.key)}</td><td>${r.val}</td></tr>`;
  }
  html += `</table></div>`;
  return html;
}

// ─── FIGURE BLOCK ─────────────────────────────────────────────
// :::figure align: right caption: "Map of the Republic"
// /images/marzena-map.png
// :::
function renderFigure(tok) {
  const args = parseInlineArgs(tok.args);
  const align = args.align || 'right';
  const caption = args.caption || '';
  const src = tok.body.trim().split('\n')[0].trim();
  const klass = align === 'left' ? 'float-left' : (align === 'none' ? '' : 'float-right');
  const resolved = resolveImagePath(src);
  return `<figure class="figure-block ${klass}">
    <img src="${resolved}" alt="${escapeAttr(caption)}" onclick="openLightbox('${resolved}','${escapeAttr(caption)}')">
    ${caption ? `<figcaption class="figure-caption">${renderInline(caption)}</figcaption>` : ''}
  </figure>`;
}

// Parse inline args like  align: right caption: "Some text"  → { align: "right", caption: "Some text" }
function parseInlineArgs(str) {
  const out = {};
  if (!str) return out;
  const re = /(\w+):\s*(?:"([^"]*)"|'([^']*)'|(\S+))/g;
  let m;
  while ((m = re.exec(str)) !== null) {
    out[m[1]] = m[2] ?? m[3] ?? m[4];
  }
  return out;
}

// ─── MARKDOWN PROSE BLOCK RENDERER ─────────────────────────────────────────────
function renderMarkdownBlock(md) {
  let html = md;

  // Tables (pipe-style)
  html = html.replace(/(\|.+\|\n)+/g, tableBlock => {
    const rows = tableBlock.trim().split('\n').filter(r => !r.match(/^\|[-| :]+\|$/));
    return '<table class="wiki-table">' + rows.map((r, i) => {
      const cells = r.split('|').slice(1, -1).map(c => c.trim());
      const tag = i === 0 ? 'th' : 'td';
      return `<tr>${cells.map(c => `<${tag}>${renderInline(c)}</${tag}>`).join('')}</tr>`;
    }).join('') + '</table>';
  });

  // Headings
  html = html.replace(/^#### (.+)$/gm, (_, t) => `<h4 id="${slugifyHeading(t)}">${renderInline(t)}</h4>`);
  html = html.replace(/^### (.+)$/gm, (_, t) => `<h3 id="${slugifyHeading(t)}">${renderInline(t)}</h3>`);
  html = html.replace(/^## (.+)$/gm, (_, t) => `<h2 id="${slugifyHeading(t)}">${renderInline(t)}</h2>`);
  html = html.replace(/^# (.+)$/gm, '<!-- title:$1 -->');

  // Blockquotes (consecutive lines)
  html = html.replace(/(?:^> .+\n?)+/gm, block => {
    const inner = block.trim().split('\n').map(l => l.replace(/^>\s?/, '')).join(' ');
    return `<blockquote>${renderInline(inner)}</blockquote>`;
  });

  // Horizontal rule
  html = html.replace(/^---$/gm, '<hr>');

  // Lists — unordered
  html = html.replace(/(?:^- .+\n?)+/gm, block => {
    const items = block.trim().split('\n').map(l => `<li>${renderInline(l.replace(/^- /, ''))}</li>`).join('');
    return `<ul>${items}</ul>`;
  });

  // Lists — ordered
  html = html.replace(/(?:^\d+\. .+\n?)+/gm, block => {
    const items = block.trim().split('\n').map(l => `<li>${renderInline(l.replace(/^\d+\.\s/, ''))}</li>`).join('');
    return `<ol>${items}</ol>`;
  });

  // Paragraphs: wrap orphan lines, applying inline rules
  const lines = html.split('\n');
  const out = [];
  let inPara = false;
  for (const raw of lines) {
    const line = raw.trim();
    if (!line) {
      if (inPara) { out.push('</p>'); inPara = false; }
      continue;
    }
    // Already-rendered HTML block elements pass through
    if (line.match(/^<(h[1-6]|ul|ol|table|blockquote|div|hr|figure|aside|section|p|!)/)) {
      if (inPara) { out.push('</p>'); inPara = false; }
      out.push(line);
    } else {
      if (!inPara) { out.push('<p>'); inPara = true; }
      out.push(renderInline(line) + ' ');
    }
  }
  if (inPara) out.push('</p>');
  return out.join('\n');
}

// ─── INLINE RENDERING ─────────────────────────────────────────────
function renderInline(text) {
  if (!text) return '';
  let s = text;

  // Images: ![alt](url) — handled before links so the ! prefix isn't mistaken
  s = s.replace(/!\[([^\]]*)\]\(([^)]+)\)/g, (_, alt, url) => {
    const resolved = resolveImagePath(url);
    return `<img src="${resolved}" alt="${escapeAttr(alt)}" style="max-width:100%;height:auto;cursor:zoom-in;" onclick="openLightbox('${resolved}','${escapeAttr(alt)}')">`;
  });

  // Bold + italic combos
  s = s.replace(/\*\*\*(.+?)\*\*\*/g, '<strong><em>$1</em></strong>');
  s = s.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>');
  s = s.replace(/(?<![*\w])\*(?!\s)([^*\n]+?)\*(?!\w)/g, '<em>$1</em>');

  // Inline code
  s = s.replace(/`([^`]+)`/g, '<code>$1</code>');

  // Wiki links: [[Article Name]] or [[slug|Display text]]
  s = s.replace(/\[\[([^\]|]+)(?:\|([^\]]+))?\]\]/g, (_, target, display) => {
    const slug = slugifyTarget(target);
    const exists = articleExists(slug);
    const text = display || target;
    const cls = exists ? '' : 'redlink';
    const title = exists ? `Read: ${target}` : `Create: ${target}`;
    return `<a class="${cls}" onclick="navigate('article','${slug}')" title="${escapeAttr(title)}">${escapeHtml(text)}</a>`;
  });

  // External links: [text](url)
  s = s.replace(/\[([^\]]+)\]\((https?:[^)]+)\)/g,
    '<a href="$2" target="_blank" rel="noopener">$1</a>');

  return s;
}

// ─── HELPERS ─────────────────────────────────────────────
function slugifyHeading(text) {
  return text.toLowerCase().replace(/[^\w\s-]/g, '').replace(/\s+/g, '-');
}

function slugifyTarget(text) {
  return text.toLowerCase().trim().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');
}

function slugToTitle(slug) {
  return slug.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
}

function articleExists(slug) {
  if (!State.index) return true; // optimistic before index loads
  return State.index.articles.some(a => a.slug === slug);
}

function escapeHtml(s) {
  return String(s ?? '').replace(/[&<>]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' }[c]));
}
function escapeAttr(s) {
  return String(s ?? '').replace(/["'<>&]/g, c => ({ '"': '&quot;', "'": '&#39;', '<': '&lt;', '>': '&gt;', '&': '&amp;' }[c]));
}

function resolveImagePath(src) {
  if (!src) return '';
  if (src.match(/^https?:/)) return src;                    // external URL
  if (src.startsWith('/')) return RAW_BASE + src;           // repo-rooted path
  return `${RAW_BASE}/${IMAGES_PATH}/${src}`;               // bare filename → /images/
}

function extractTitle(md) {
  const body = extractFrontmatter(md).body;
  const m = body.match(/^# (.+)$/m);
  return m ? m[1].trim() : null;
}

function extractSummary(md) {
  const body = extractFrontmatter(md).body;
  // Strip ::: blocks first so we don't summarize an infobox row
  const stripped = body.replace(/:::[\s\S]*?:::/g, '');
  const lines = stripped.split('\n');
  let pastTitle = false;
  for (const l of lines) {
    if (!pastTitle && l.startsWith('# ')) { pastTitle = true; continue; }
    const trimmed = l.trim();
    if (pastTitle && trimmed && !trimmed.startsWith('#')) {
      // Strip wiki-link brackets for clean summary
      const clean = trimmed.replace(/\[\[([^\]|]+)(?:\|[^\]]+)?\]\]/g, '$1').replace(/\*\*?/g, '');
      return clean.length > 160 ? clean.slice(0, 160) + '…' : clean;
    }
  }
  return '';
}

// ═══════════════════════════════════════════════════════════════
// VIEW: HOME / PORTAL
// ═══════════════════════════════════════════════════════════════
async function showHome() {
  document.getElementById('main-content').innerHTML = '<div class="loading">Loading the Republic</div>';
  document.title = 'Marzenapedia — Main Page';
  document.getElementById('breadcrumb').innerHTML = '';

  const index = await fetchIndex();
  const articles = index.articles || [];

  if (articles.length === 0) {
    document.getElementById('main-content').innerHTML = `
      <div class="portal">
        ${portalHero()}
        <div class="notice-box">No articles found yet. The <code>articles/</code> folder is empty, or <code>index.json</code> hasn't been generated yet. Click <strong>+ New Article</strong> to write the first.</div>
        <div class="article-card" onclick="openNewArticle()" style="border-style:dashed;">
          <div><h3>+ Create the first article</h3><p>Open the editor to begin Marzenapedia.</p></div>
        </div>
      </div>`;
    return;
  }

  // Pick a few featured articles + recent
  const recent = [...articles].sort((a, b) => {
    const da = new Date(a.last_edited || 0).getTime();
    const db = new Date(b.last_edited || 0).getTime();
    return db - da;
  }).slice(0, 6);

  const cardsHtml = recent.map(c => `
    <div class="article-card" onclick="navigate('article','${c.slug}')">
      <div>
        <h3>${escapeHtml(c.title)}</h3>
        <p>${escapeHtml(c.summary || '')}</p>
      </div>
      <div class="meta">
        ${c.last_edited ? new Date(c.last_edited).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }) : ''}
        ${(c.tags || []).slice(0, 2).map(t => `<span class="tag">${escapeHtml(t)}</span>`).join('')}
      </div>
    </div>`).join('');

  // Tag tally for the sidebar
  const tagCounts = {};
  articles.forEach(a => (a.tags || []).forEach(t => { tagCounts[t] = (tagCounts[t] || 0) + 1; }));
  const topTags = Object.entries(tagCounts).sort((a, b) => b[1] - a[1]).slice(0, 8);

  document.getElementById('main-content').innerHTML = `
    <div class="portal">
      ${portalHero()}
      <div class="portal-grid">
        <div class="portal-main">
          <h2>Recently Updated</h2>
          ${cardsHtml}
          <div class="article-card" onclick="navigate('all')" style="border-style:dashed;background:transparent;">
            <div><h3 style="color:var(--muted);">Browse all ${articles.length} articles →</h3></div>
          </div>
        </div>
        <aside class="portal-side">
          <div class="side-block">
            <h3>The Republic</h3>
            <p style="font-style:italic;">A semi-presidential republic of the North African seaboard, founded 2 May 1952. Capital: Lévane. Population: ~41 million.</p>
          </div>
          ${topTags.length ? `<div class="side-block">
            <h3>Topics</h3>
            <ul>${topTags.map(([t, n]) => `<li><a onclick="navigate('search','${escapeAttr(t)}')">${escapeHtml(t)} <span style="color:var(--muted-soft);font-size:12px;">·&nbsp;${n}</span></a></li>`).join('')}</ul>
          </div>` : ''}
          <div class="side-block">
            <h3>Bureau of Records</h3>
            <p>Marzenapedia is maintained by the Bureau of Records, Lévane.</p>
            <p style="margin-top:8px;font-size:12px;color:var(--muted-soft);">Last index rebuild: ${index.generated_at ? new Date(index.generated_at).toLocaleString('en-GB', { timeZone: 'Europe/Paris' }) + ' CET' : 'unknown'}</p>
          </div>
        </aside>
      </div>
    </div>`;
}

function portalHero() {
  return `
    <div class="portal-hero">
      <div class="portal-hero-inner">
        <h1>Marzenapedia</h1>
        <div class="founding">
          A nation of its own civilisation, heir to no single tradition.<br>
          What follows is the Republic's record of itself —<br>
          its institutions, its history, its conflicts and its silences.
        </div>
        <div class="attribution">— Bureau of Records, Lévane · Founded 2 May 1952</div>
      </div>
    </div>`;
}

// ═══════════════════════════════════════════════════════════════
// VIEW: ALL ARTICLES
// ═══════════════════════════════════════════════════════════════
async function showAllArticles() {
  document.getElementById('main-content').innerHTML = '<div class="loading">Loading article index</div>';
  document.title = 'All Articles — Marzenapedia';
  document.getElementById('breadcrumb').innerHTML = '';

  const index = await fetchIndex();
  const articles = [...(index.articles || [])].sort((a, b) => a.title.localeCompare(b.title));

  // Group by first letter
  const groups = {};
  articles.forEach(a => {
    const letter = (a.title[0] || '#').toUpperCase();
    const key = /[A-Z]/.test(letter) ? letter : '#';
    (groups[key] = groups[key] || []).push(a);
  });
  const letters = Object.keys(groups).sort();

  const groupsHtml = letters.map(letter => `
    <h3 style="font-family:'Crimson Pro',serif;font-size:24px;color:var(--gold);border-bottom:1px solid var(--border);padding-bottom:4px;margin:24px 0 12px;font-weight:700;">${letter}</h3>
    ${groups[letter].map(a => `
      <div class="search-result-item" onclick="navigate('article','${a.slug}')">
        <h3>${escapeHtml(a.title)}</h3>
        <p>${escapeHtml(a.summary || '')}</p>
      </div>`).join('')}`).join('');

  document.getElementById('main-content').innerHTML = `
    <div class="search-results">
      <h2>All Articles · ${articles.length}</h2>
      ${groupsHtml || '<div class="notice-box">No articles yet.</div>'}
      <div class="article-card" onclick="openNewArticle()" style="border-style:dashed;margin-top:28px;background:transparent;">
        <div><h3 style="color:var(--muted);">+ New Article</h3><p>Open the editor to add to Marzenapedia.</p></div>
      </div>
    </div>`;
}

// ═══════════════════════════════════════════════════════════════
// VIEW: SEARCH RESULTS (full page, distinct from instant dropdown)
// ═══════════════════════════════════════════════════════════════
async function showSearchResults(q) {
  if (!q) { navigate('home'); return; }
  document.getElementById('main-content').innerHTML = '<div class="loading">Searching the archive</div>';
  document.title = `Search: ${q} — Marzenapedia`;
  document.getElementById('breadcrumb').innerHTML = `<a onclick="navigate('home')">Main Page</a><span class="sep">·</span>Search: <em>${escapeHtml(q)}</em>`;

  const index = await fetchIndex();
  const articles = index.articles || [];
  const ql = q.toLowerCase();

  // Index-level matches first (cheap)
  const indexHits = articles.filter(a =>
    a.title.toLowerCase().includes(ql) ||
    (a.summary || '').toLowerCase().includes(ql) ||
    (a.tags || []).some(t => t.toLowerCase().includes(ql))
  );

  // Full-text search the rest (more expensive — fetch on demand)
  const matched = new Set(indexHits.map(a => a.slug));
  const fullTextResults = await Promise.all(articles
    .filter(a => !matched.has(a.slug))
    .slice(0, 50) // cap to keep things sane
    .map(async a => {
      try {
        const md = await fetchArticle(a.slug);
        const lower = md.toLowerCase();
        if (lower.includes(ql)) {
          const idx = lower.indexOf(ql);
          const snippet = md.slice(Math.max(0, idx - 70), idx + 130).replace(/\n/g, ' ');
          return { ...a, snippet };
        }
        return null;
      } catch { return null; }
    }));

  const fullHits = fullTextResults.filter(Boolean);

  const allResults = [
    ...indexHits.map(a => ({ ...a, snippet: a.summary })),
    ...fullHits
  ];

  if (allResults.length === 0) {
    document.getElementById('main-content').innerHTML = `
      <div class="search-results">
        <h2>No results for "${escapeHtml(q)}"</h2>
        <p style="color:var(--muted);font-family:'Crimson Pro',serif;font-style:italic;">No articles matched. <a onclick="openNewArticle()" style="color:var(--link);cursor:pointer;">Create a new article →</a></p>
      </div>`;
    return;
  }

  const re = new RegExp(escapeRegex(q), 'gi');
  const rows = allResults.map(r => `
    <div class="search-result-item" onclick="navigate('article','${r.slug}')">
      <h3>${r.title.replace(re, m => `<mark>${m}</mark>`)}</h3>
      <p>…${(r.snippet || '').replace(re, m => `<mark>${m}</mark>`)}…</p>
    </div>`).join('');

  document.getElementById('main-content').innerHTML = `
    <div class="search-results">
      <h2>Search results for "${escapeHtml(q)}" · ${allResults.length}</h2>
      ${rows}
    </div>`;
}

function escapeRegex(s) { return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); }

// ═══════════════════════════════════════════════════════════════
// VIEW: ARTICLE
// ═══════════════════════════════════════════════════════════════
async function showArticle(slug, sectionAnchor) {
  document.getElementById('main-content').innerHTML = '<div class="loading">Loading article</div>';
  document.title = `${slugToTitle(slug)} — Marzenapedia`;

  await fetchIndex(); // ensure index is loaded for redlink detection

  let md;
  try {
    md = await fetchArticle(slug);
  } catch (e) {
    renderArticleNotFound(slug);
    return;
  }

  const fm = parseFrontmatter(md);
  const title = extractTitle(md) || slugToTitle(slug);
  document.title = `${title} — Marzenapedia`;

  // Strip the title line from body so we don't render it twice
  const body = extractFrontmatter(md).body.replace(/^# .+\n/, '');
  const bodyHtml = parseMarkdown(body);

  // Build TOC from h2 elements
  const tocHtml = buildToc(bodyHtml);

  // Last-edited date
  const lastEdited = await fetchLastEdited(slug);
  const editedStr = lastEdited
    ? new Date(lastEdited).toLocaleDateString('en-GB', { timeZone: 'Europe/Paris', day: 'numeric', month: 'long', year: 'numeric' })
    : null;

  // Article meta line (in-universe date, last edited, sources)
  const metaParts = [];
  if (fm.date) metaParts.push(`<span class="meta-item">${formatInUniverseDate(fm.date)}</span>`);
  if (editedStr) metaParts.push(`<span class="meta-item">Last revised ${editedStr}</span>`);
  if (fm.tags && fm.tags.length) metaParts.push(`<span class="meta-item">${fm.tags.join(' · ')}</span>`);
  const metaHtml = metaParts.length ? `<div class="article-meta">${metaParts.join('')}</div>` : '';

  // Named sources block (foundation for full named-source system in later phases)
  let sourcesHtml = '';
  if (fm.sources && fm.sources.length) {
    sourcesHtml = `<div style="margin-top:36px;padding:14px 18px;background:var(--paper-warm);border-left:3px solid var(--gold);font-family:'Crimson Pro',serif;font-size:14px;">
      <strong style="font-family:'Source Sans 3',sans-serif;font-size:11px;text-transform:uppercase;letter-spacing:0.08em;color:var(--navy);display:block;margin-bottom:6px;">Cited Sources</strong>
      <ul style="margin:0 0 0 18px;font-style:italic;">
        ${fm.sources.map(s => `<li>${escapeHtml(s)}</li>`).join('')}
      </ul>
    </div>`;
  }

  // Breadcrumb
  document.getElementById('breadcrumb').innerHTML =
    `<a onclick="navigate('home')">Main Page</a><span class="sep">·</span><a onclick="navigate('all')">All Articles</a><span class="sep">·</span>${escapeHtml(title)}`;

  document.getElementById('main-content').innerHTML = `
    <div class="layout">
      ${tocHtml}
      <article class="article clearfix">
        <div class="article-title">${escapeHtml(title)}</div>
        ${metaHtml}
        ${bodyHtml}
        ${sourcesHtml}
        <div style="clear:both;border-top:1px solid var(--border);margin-top:36px;padding-top:14px;font-size:11px;color:var(--muted-soft);font-style:italic;font-family:'Crimson Pro',serif;letter-spacing:0.02em;">
          Marzenapedia &nbsp;·&nbsp; Bureau of Records, Lévane &nbsp;·&nbsp; Fictional sovereign state
        </div>
      </article>
    </div>`;

  // Active TOC highlighting via IntersectionObserver
  setupScrollSpy();

  // Scroll to section anchor (#section after slug)
  if (sectionAnchor) {
    const target = document.getElementById(sectionAnchor);
    if (target) target.scrollIntoView({ behavior: 'smooth' });
  } else {
    window.scrollTo({ top: 0, behavior: 'auto' });
  }
}

function renderArticleNotFound(slug) {
  document.getElementById('main-content').innerHTML = `
    <div class="error-msg">
      <h2>Article Not Found</h2>
      <p>The article "<strong>${escapeHtml(slug)}</strong>" does not exist yet in Marzenapedia.</p>
      <p style="margin-top:14px;"><a onclick="openNewArticle('${slug}')" style="color:var(--link);cursor:pointer;text-decoration:underline;">Create this article →</a></p>
      <p style="margin-top:8px;"><a onclick="navigate('home')" style="color:var(--muted);cursor:pointer;">← Return to the Main Page</a></p>
    </div>`;
  document.getElementById('breadcrumb').innerHTML = `<a onclick="navigate('home')">Main Page</a><span class="sep">·</span>Not found`;
}

function buildToc(html) {
  const matches = [...html.matchAll(/<h2 id="([^"]+)">([^<]+)<\/h2>/g)];
  if (matches.length < 2) return '';
  const items = matches.map(m =>
    `<li><a href="#/${State.slug}#${m[1]}" data-toc-target="${m[1]}">${m[2]}</a></li>`
  ).join('');
  return `<nav class="toc-sidebar"><h3>Contents</h3><ol>${items}</ol></nav>`;
}

// Active TOC highlight as the user scrolls
function setupScrollSpy() {
  const sections = document.querySelectorAll('.article h2[id]');
  const links = document.querySelectorAll('.toc-sidebar a[data-toc-target]');
  if (!sections.length || !links.length) return;

  const linkMap = {};
  links.forEach(l => { linkMap[l.dataset.tocTarget] = l; });

  State.scrollObserver = new IntersectionObserver(entries => {
    entries.forEach(entry => {
      const link = linkMap[entry.target.id];
      if (!link) return;
      if (entry.isIntersecting) {
        links.forEach(l => l.classList.remove('active-toc'));
        link.classList.add('active-toc');
      }
    });
  }, { rootMargin: '-20% 0px -70% 0px' });

  sections.forEach(s => State.scrollObserver.observe(s));
}

// ═══════════════════════════════════════════════════════════════
// SEARCH (instant dropdown + Enter→full results)
// ═══════════════════════════════════════════════════════════════
function onSearchInput() {
  const q = document.getElementById('search-input').value.trim();
  const dd = document.getElementById('search-dropdown');
  clearTimeout(State.searchDebounceTimer);
  if (!q) { dd.classList.remove('visible'); return; }
  State.searchDebounceTimer = setTimeout(() => runInstantSearch(q), 100);
}

function runInstantSearch(q) {
  if (!State.index) return;
  const ql = q.toLowerCase();
  const dd = document.getElementById('search-dropdown');
  const articles = State.index.articles || [];

  const hits = articles.filter(a =>
    a.title.toLowerCase().includes(ql) ||
    (a.summary || '').toLowerCase().includes(ql) ||
    (a.tags || []).some(t => t.toLowerCase().includes(ql))
  ).slice(0, 8);

  if (hits.length === 0) {
    dd.innerHTML = `<div class="no-results">No quick matches. Press Enter for full-text search.</div>`;
    dd.classList.add('visible');
    return;
  }

  State.searchActiveResult = -1;
  dd.innerHTML = hits.map((h, i) => `
    <div class="result" data-slug="${h.slug}" data-index="${i}" onclick="navigate('article','${h.slug}');document.getElementById('search-dropdown').classList.remove('visible');document.getElementById('search-input').value='';">
      <div class="result-title">${escapeHtml(h.title)}</div>
      <div class="result-snippet">${escapeHtml(h.summary || '')}</div>
    </div>`).join('');
  dd.classList.add('visible');
}

function onSearchKeydown(e) {
  const dd = document.getElementById('search-dropdown');
  const results = dd.querySelectorAll('.result');

  if (e.key === 'ArrowDown') {
    e.preventDefault();
    State.searchActiveResult = Math.min(State.searchActiveResult + 1, results.length - 1);
    updateActiveResult(results);
  } else if (e.key === 'ArrowUp') {
    e.preventDefault();
    State.searchActiveResult = Math.max(State.searchActiveResult - 1, -1);
    updateActiveResult(results);
  } else if (e.key === 'Enter') {
    e.preventDefault();
    if (State.searchActiveResult >= 0 && results[State.searchActiveResult]) {
      const slug = results[State.searchActiveResult].dataset.slug;
      navigate('article', slug);
      dd.classList.remove('visible');
      e.target.value = '';
    } else {
      doSearch();
    }
  } else if (e.key === 'Escape') {
    dd.classList.remove('visible');
    e.target.blur();
  }
}

function updateActiveResult(results) {
  results.forEach((r, i) => r.classList.toggle('active', i === State.searchActiveResult));
  if (State.searchActiveResult >= 0) {
    results[State.searchActiveResult].scrollIntoView({ block: 'nearest' });
  }
}

function doSearch() {
  const q = document.getElementById('search-input').value.trim();
  if (!q) return;
  document.getElementById('search-dropdown').classList.remove('visible');
  navigate('search', q);
}

// ═══════════════════════════════════════════════════════════════
// LIGHTBOX
// ═══════════════════════════════════════════════════════════════
function openLightbox(src, caption) {
  const lb = document.getElementById('lightbox');
  const img = document.getElementById('lightbox-img');
  const cap = document.getElementById('lightbox-caption');
  img.src = src;
  if (caption) {
    cap.innerHTML = caption;
    cap.style.display = 'block';
  } else {
    cap.style.display = 'none';
  }
  lb.classList.add('visible');
  document.body.style.overflow = 'hidden';
}

function closeLightbox() {
  document.getElementById('lightbox').classList.remove('visible');
  document.body.style.overflow = '';
}

// ═══════════════════════════════════════════════════════════════
// EDITOR
// ═══════════════════════════════════════════════════════════════
function openEditor() {
  if (!State.slug) { openNewArticle(); return; }
  fetchArticle(State.slug).then(md => {
    document.getElementById('editor-filename').value = State.slug;
    document.getElementById('editor-content').value = md;
    document.getElementById('editor-title').textContent = `Edit: ${slugToTitle(State.slug)}`;
    document.getElementById('editor-overlay').classList.add('visible');
  }).catch(() => {
    document.getElementById('editor-filename').value = State.slug;
    document.getElementById('editor-content').value = `# ${slugToTitle(State.slug)}\n\nWrite your article here.\n`;
    document.getElementById('editor-title').textContent = `Edit: ${slugToTitle(State.slug)}`;
    document.getElementById('editor-overlay').classList.add('visible');
  });
}

function openNewArticle(slug) {
  const s = slug || '';
  document.getElementById('editor-filename').value = s;
  document.getElementById('editor-content').value = s
    ? `:::frontmatter\ntags: \ndate: \nsources: \n:::\n\n# ${slugToTitle(s)}\n\nWrite your article here.\n`
    : `:::frontmatter\ntags: \ndate: \nsources: \n:::\n\n# Article Title\n\nWrite your article here.\n`;
  document.getElementById('editor-title').textContent = 'New Article';
  document.getElementById('editor-overlay').classList.add('visible');
}

function closeEditor() {
  document.getElementById('editor-overlay').classList.remove('visible');
}

function previewArticle() {
  const md = document.getElementById('editor-content').value;
  const slug = (document.getElementById('editor-filename').value || 'preview').toLowerCase().replace(/\s+/g, '-');
  State.articleCache[slug] = md;
  closeEditor();
  navigate('article', slug);
}

function saveArticle() {
  const slug = document.getElementById('editor-filename').value.trim().toLowerCase().replace(/\s+/g, '-');
  const content = document.getElementById('editor-content').value;
  if (!slug) { alert('Please enter a slug for the article.'); return; }
  if (!content.trim()) { alert('Article content is empty.'); return; }

  const filename = `${ARTICLES_PATH}/${slug}.md`;
  const encoded = encodeURIComponent(content);
  const githubUrl = `https://github.com/${REPO_OWNER}/${REPO_NAME}/new/${BRANCH}?filename=${encodeURIComponent(filename)}&value=${encoded}`;

  alert(`Opening GitHub to save this article.\n\nFile: ${filename}\n\nIf the file already exists, GitHub will let you edit the existing version. Once you commit, the index will rebuild automatically.`);
  window.open(githubUrl, '_blank');

  State.articleCache[slug] = content;
  State.index = null; // invalidate
  closeEditor();
}

// ═══════════════════════════════════════════════════════════════
// NAV / TABS / HELP
// ═══════════════════════════════════════════════════════════════
function switchTab(tab) {
  if (tab === 'article') {
    document.getElementById('tab-article').classList.add('active');
    document.getElementById('tab-edit').classList.remove('active');
  }
}

function showHelp() {
  document.getElementById('help-overlay').classList.add('visible');
}

async function buildNav() {
  const index = await fetchIndex();
  const articles = index.articles || [];
  const nav = document.getElementById('main-nav');

  // Pick a few "backbone" articles for the nav — preferring ones tagged 'backbone' or 'foundational'
  const backbone = articles.filter(a => (a.tags || []).some(t => /backbone|foundational/i.test(t)));
  const featured = backbone.length >= 4 ? backbone.slice(0, 4) : articles.slice(0, 4);

  nav.innerHTML = featured.map(a =>
    `<a onclick="navigate('article','${a.slug}')">${escapeHtml(a.title.split(' ')[0])}</a>`
  ).join('') + `<a onclick="navigate('all')">All Articles</a>`;
}

// ═══════════════════════════════════════════════════════════════
// KEYBOARD SHORTCUTS
// ═══════════════════════════════════════════════════════════════
document.addEventListener('keydown', e => {
  // "/" focuses search (unless typing in an input)
  if (e.key === '/' && !['INPUT', 'TEXTAREA'].includes(e.target.tagName)) {
    e.preventDefault();
    document.getElementById('search-input').focus();
  }
  // Esc closes lightbox or modals
  if (e.key === 'Escape') {
    closeLightbox();
    closeEditor();
    document.getElementById('help-overlay').classList.remove('visible');
  }
});

// ═══════════════════════════════════════════════════════════════
// INIT
// ═══════════════════════════════════════════════════════════════
(async function init() {
  initTheme();
  startCetClock();
  await fetchIndex();
  await buildNav();
  await handleRoute();
})();

// Expose functions to inline event handlers (for files served as ES modules in future)
window.navigate = navigate;
window.toggleTheme = toggleTheme;
window.onSearchInput = onSearchInput;
window.onSearchKeydown = onSearchKeydown;
window.doSearch = doSearch;
window.openEditor = openEditor;
window.openNewArticle = openNewArticle;
window.closeEditor = closeEditor;
window.previewArticle = previewArticle;
window.saveArticle = saveArticle;
window.switchTab = switchTab;
window.showHelp = showHelp;
window.openLightbox = openLightbox;
window.closeLightbox = closeLightbox;
